# Site settings
title: Salyent Research Group
description: Salyent Research Group
#baseurl: "/brodyu.github.io" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Salyent Research Group
user_description:
user_title: Software Developer
email: buehara@salyentresearch.com
github_username:  brodyu
linkedin_url: https://www.linkedin.com/in/brodyu

# Google-analytics
google-analytics:
  id: "UA-160596761-1"

exclude: ['package.json', 'src' , 'node_modules']
